# Generated by Django 3.0.1 on 2020-05-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relational_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('my_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relational_db.school')),
            ],
        ),
    ]
